cache:
  paths:
    - node_modules/
    - yarn.lock

stages:
  - test
  - publish

test:
  stage: test
  script:
    - "npm i"
    - "npm run lint:strict"
  tags:
    - npm

npm:
  stage: publish
  script:
    - "npm publish"
  only:
    - master
  tags:
    - npm
